#pragma once

#include "NativeGameplayTags.h"

namespace CMGameplayTags
{
	/**** Widget Stack Tags ****/
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_Modal)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_GameMenu)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_GameHUD)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_Frontend)

	/**** Widgets Tags ****/
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_PressAnyKeyScreen)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_MainMenuScreen)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_StartGameScreen)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_OptionsScreen)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_CreditsScreen)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_ConfirmScreen)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_KeyRemapScreen)
	
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_InGameLayoutScreen)
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_InGameMenuScreen)

	/**** Image Tags ****/
	COMMONMENU_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Image_TestImage)
}
